# Spring configuration for CI
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Service discovery configuration for CI
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false

# Messaging configuration for CI
rabbitmq:
  queues:
    platform-emails: dummy-queue

# AWS configuration for CI
aws:
  access-key: dummy-key
  secret-key: dummy-secret
  ses:
    region: dummy-region

# Email configuration for CI
email:
  from-email: test@example.com
  frontend-base-url: http://localhost:3000

# Observability configuration for CI
management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics