# Server properties
server:
  port: 8160

# Information for the info endpoint
info:
  app:
    environment: DEV
    name: ${spring.application.name}
    description: Email Service - Local Instance

# Spring application properties
spring:
  application:
    name: comms-email
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:discovery://config-server
      - optional:file:./env.properties
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}

# AWS configuration
aws:
  accessKey: ${AWS_ACCESS_KEY:dummy-key}
  secretKey: ${AWS_SECRET_KEY:dummy-secret}
  ses:
    region: ${AWS_SES_REGION:dummy-region}

# Email configuration
email:
  fromEmail: ${FROM_EMAIL:test@example.com}

# Frontend configuration
frontend:
  baseUrl: ${FRONTEND_BASE_URL:http://localhost:3077}

# Eureka configuration
eureka:
  client:
    fetchRegistry: ${EUREKA_DISCOVERY_ENABLED:false}
    registerWithEureka: ${EUREKA_DISCOVERY_ENABLED:false}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

# RabbitMQ settings
rabbitmq:
  exchange: ${RMQ_EXCHANGE:dummy-exchange}
  queues:
    platform-emails: ${RMQ_PLATFORM_EMAILS_Q:dummy-queue}
  routing-keys:
    platform-emails: ${RMQ_PLATFORM_EMAILS_RK:dummy-key}
# Management properties
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, refresh

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.mariuszilinskas.vsp: DEBUG
