# Spring application properties for CI
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# AWS configuration for CI
aws:
  accessKey: dummy-key
  secretKey: dummy-secret
  ses:
    region: dummy-region

# Email configuration for CI
email:
  fromEmail: test@example.com

# Frontend configuration for CI
frontend:
  baseUrl: http://localhost:3000

# Eureka configuration for CI
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false

# RabbitMQ settings for CI
rabbitmq:
  exchange: dummy-exchange
  queues:
    platform-emails: dummy-queue
  routing-keys:
    platform-emails: dummy-key
